version: "3.4"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - mysql
      - php

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      # MYSQL_USER: username
      # MYSQL_PASSWORD: password
    restart: on-failure

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: on-failure
    links:
      - mysql
    depends_on:
      - mysql

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql

  # composer:
  #   image: composer
  #   volumes:
  #     - ./app:/app
  #   restart: 'no'
  #   command: install
